### ISSUE TITLE
Try enable FlexSearch

### ISSUE THREAD

**Issue by shuding** [spencerwooo/onedrive-vercel-index-docs#7]
It would be great to enable the new built-in FlexSearch in latest `nextra` and `nextra-theme-docs` alpha version:
- https://github.com/vercel/swr-site/blob/c787a52a1f7bc434f18aa5a7426be2ca0869c26a/theme.config.js#L40
- https://github.com/vercel/swr-site/blob/c787a52a1f7bc434f18aa5a7426be2ca0869c26a/next.config.js#L4

One breaking change is you'll need to change `type: "nav"` to `type: "page"` in your meta.json files.

Let me know if you run into any problems!

**Comment by spencerwooo** [comment]
Wow! Thanks for the update. I also noticed the bug that issue mentioned, but I thought it was caused by some config issue on my side. I'll try this over the weekend. ❤️

**Comment by spencerwooo** [comment]
Updated! Thanks for your awesome work :) @shuding
